import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, MapPin, ShieldCheck, Truck } from 'lucide-react';
import RelatedServices from '@/components/ui/RelatedServices';

const included = ['Furniture wrapping and protection', 'Packing materials and full packing support', 'Loading and unloading for large items', 'Fleet vehicles sized for the job', 'Clear communication from start to finish'];
const steps = [
  { icon: MapPin, title: 'Plan around Johannesburg', copy: 'We account for heavy traffic routes, estate access protocols, lift bookings, and building regulations before moving day.' },
  { icon: ShieldCheck, title: 'Load with purpose', copy: 'Our teams bring the right materials and experience to protect furniture, appliances, office equipment, and every fragile detail.' },
  { icon: Truck, title: 'Arrive ready', copy: 'From household relocations to corporate offices, we keep the move punctual, secure, and clearly communicated.' },
];

export const metadata = { title: 'Home & Office Moving | Charloxy Transport', description: 'Residential and commercial moving services across greater Johannesburg.' };

export default function HomeOfficeMovingPage() {
  return <main className="overflow-hidden bg-background">
    <section className="container-wide pb-20 pt-8 md:pb-24 md:pt-14"><Link href="/services" className="inline-flex items-center gap-2 text-sm font-semibold text-ink-muted hover:text-navy"><ArrowLeft size={16} /> All services</Link><div className="mt-8 grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-end lg:gap-16"><div><p className="font-display text-sm uppercase tracking-[.2em] text-gold">01 / Johannesburg moving</p><h1 className="display-tight mt-5 max-w-3xl text-6xl text-navy md:text-8xl">Move with a plan. <span className="text-gold">Arrive with ease.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-ink-muted">Moving across Johannesburg requires practical knowledge of the city&apos;s logistics, including heavy traffic routes, strict estate access protocols, and building regulations.</p><Link href="/quote" className="mt-8 inline-flex items-center gap-3 rounded-full bg-gold px-6 py-3 font-semibold text-navy">Plan your move <ArrowRight size={18} /></Link></div><div className="photo-card relative min-h-[390px] bg-navy md:min-h-[520px]"><img src="/moving_truck.jpg" alt="Movers carrying furniture into a new home" className="absolute inset-0 size-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-navy/90 via-navy/15 to-transparent" /><p className="absolute bottom-6 left-6 max-w-xs font-display text-3xl uppercase leading-none text-background">Residential or commercial. Handled properly.</p></div></div></section>
    <section className="border-y border-navy/10 bg-navy py-7 text-background"><div className="container-wide flex flex-col items-center justify-between gap-6 md:flex-row"><div className="flex items-center gap-5"><img src="/insurance%20badge.png" alt="Transit insurance badge" className="size-20 shrink-0 object-contain" /><div><p className="font-display text-sm uppercase tracking-[.18em] text-gold">Fully protected moves</p><p className="mt-1 font-display text-4xl uppercase leading-none text-background md:text-5xl">R150k <span className="text-gold">Transit Insurance.</span></p></div></div><div className="flex flex-col items-center gap-3 text-center md:items-end md:text-right"><p className="max-w-md text-sm leading-6 text-background/70">Every move is covered by up to R150,000 in Goods in Transit Insurance at no extra cost.</p><Link href="/quote" className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-2.5 text-sm font-bold text-navy">Move with confidence <ArrowRight size={15} /></Link></div></div></section>
    <section className="container-wide py-20 md:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="font-display text-sm uppercase tracking-[.14em] text-gold">The right people and equipment</p><h2 className="display-tight mt-3 text-5xl text-navy md:text-7xl">A move built around <span className="text-gold">your reality.</span></h2></div><div><p className="text-lg leading-8 text-ink-muted">We provide structured residential and commercial moving services throughout the greater Johannesburg area, covering suburbs like Sandton, Randburg, Midrand, and Bedfordview.</p><p className="mt-5 text-lg leading-8 text-ink-muted">Whether relocating a corporate office or moving your household, our teams manage the physical requirements of the transition. We supply the necessary fleet vehicles, moving materials, and personnel for large furniture removals, equipment transport, and full-scale packing. Our focus is entirely on punctuality, secure loading, and clear communication from start to finish.</p></div></div></section>
    <section className="bg-paper py-20 md:py-28"><div className="container-wide"><p className="font-display text-sm uppercase tracking-[.14em] text-gold">How it works</p><h2 className="display-tight mt-3 max-w-3xl text-5xl text-navy md:text-7xl">Less disruption. <span className="text-gold">More control.</span></h2><div className="mt-12 grid gap-5 lg:grid-cols-3">{steps.map(({ icon: Icon, title, copy }, index) => <article key={title} className="rounded-2xl bg-background p-7 md:p-8"><div className="flex items-center justify-between"><span className="font-mono text-xs text-ink-muted">0{index + 1}</span><span className="grid size-11 place-items-center rounded-full bg-gold text-navy"><Icon size={20} /></span></div><h3 className="mt-16 font-display text-3xl uppercase text-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-ink-muted">{copy}</p></article>)}</div></div></section>
    <section className="container-wide py-20 md:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="font-display text-sm uppercase tracking-[.14em] text-gold">Included in the move</p><h2 className="display-tight mt-3 text-5xl text-navy md:text-6xl">Big jobs, <span className="text-gold">properly covered.</span></h2></div><ul className="grid gap-0">{included.map(item => <li key={item} className="flex items-center gap-4 border-b border-navy/15 py-5 text-base font-semibold text-navy"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-gold"><Check size={16} /></span>{item}</li>)}</ul></div></section>
    <RelatedServices /><section className="container-wide pb-20"><div className="flex flex-col gap-6 rounded-[1.5rem] bg-navy p-8 md:flex-row md:items-center md:justify-between md:p-12"><div><p className="font-display text-4xl uppercase text-background md:text-5xl">Ready to move?</p><p className="mt-3 max-w-lg text-sm leading-6 text-background/70">Tell us what is moving, where it is going, and when you need a hand.</p></div><Link href="/quote" className="inline-flex shrink-0 items-center gap-3 rounded-full bg-gold px-6 py-3 font-semibold text-navy">Get an estimate <ArrowRight size={18} /></Link></div></section>
  </main>;
}
