import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';

const services = [
  ['Home & Office Moving', 'Moving requires careful planning. Our residential and office moving teams assist with packing, loading, transportation, and offloading to ensure a smooth, stress-free relocation with minimal downtime.', 'home-office-moving'],
  ['Furniture & Appliance Deliveries', 'Bought new furniture or moving a fridge? We specialise in transporting bulky single items quickly and safely. Ideal for clients who only need a few items transported.', 'furniture-appliance-deliveries'],
  ['Collections & Deliveries', 'Time-sensitive collection and delivery services for parcels and important goods. We plan every route to ensure safe and timely delivery.', 'collections-deliveries'],
  ['Building Material Transport', 'Reliable transport for construction materials. We help Johannesburg contractors and DIY enthusiasts get their supplies to the site efficiently.', 'building-material-transport'],
  ['General Goods Transport', 'Flexible transport solutions. If it fits in our vehicles, we can move it securely, keeping every item safe along the way.', 'general-goods-transport'],
  ['Transport Services for Businesses', 'Business relocations and regular transport contracts require careful planning. We work with companies across Gauteng to ensure organized, efficient, and professionally managed logistics.', 'business-transport'],
];

export default function Services() {
  return <main className="overflow-hidden bg-background"><section className="container-wide pt-10 pb-20 md:pt-16 md:pb-28"><div className="flex flex-col gap-7 border-b border-navy/15 pb-12 md:flex-row md:items-end md:justify-between"><div><p className="font-display text-sm uppercase tracking-[.15em] text-gold">Our capabilities</p><h1 className="display-tight mt-4 max-w-4xl text-6xl text-navy md:text-8xl">Professional Transport & <span className="text-gold">Logistics.</span></h1></div><p className="max-w-md text-base leading-7 text-ink-muted">Charloxy Transport provides a full range of removals and logistics services tailored to different moving needs across Gauteng.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([title, description, slug], index) => <Link href={`/services/${slug}`} key={title} className="group flex min-h-[310px] flex-col rounded-2xl bg-paper p-7 transition-colors hover:bg-gold md:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs text-gold group-hover:text-navy/60">0{index + 1}</span><span className="grid size-10 place-items-center rounded-full border border-navy/15 text-navy transition-transform group-hover:rotate-45"><ArrowUpRight size={18} /></span></div><div className="mt-auto"><h2 className="max-w-sm font-display text-4xl uppercase leading-[.95] text-navy">{title}</h2><p className="mt-4 max-w-sm text-sm leading-6 text-ink-muted group-hover:text-navy/75">{description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-navy">Explore service <ArrowRight size={16} /></span></div></Link>)}</div><div className="mt-16 flex flex-col items-start justify-between gap-5 rounded-2xl bg-navy p-8 md:flex-row md:items-center md:p-10"><p className="font-display text-3xl uppercase text-background md:text-4xl">Need a service not listed here?</p><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-semibold text-navy">Contact us <ArrowRight size={16} /></Link></div></section></main>;
}
