import Link from 'next/link';
import { ArrowUpRight, ArrowRight } from 'lucide-react';

const services = [
  ['Home & Office Moving', 'Whether you are moving down the street or across the city, our team ensures your belongings are packed, transported, and unpacked with care.', 'home-office-moving'],
  ['Furniture & Appliance Deliveries', 'Bought new furniture or need to move a fridge? We provide safe and fast delivery services for bulky items directly to your door.', 'furniture-appliance-deliveries'],
  ['Collections & Deliveries', 'General collection and delivery services for parcels, packages, and important goods that need to arrive on time.', 'collections-deliveries'],
  ['Building Material Transport', 'Reliable transport for construction materials. We help contractors and DIY enthusiasts get their supplies to the site efficiently.', 'building-material-transport'],
  ['General Goods Transport', 'Flexible transport solutions for a wide variety of goods. If it fits in our vehicles, we can move it safely.', 'general-goods-transport'],
  ['Transport Services for Businesses', 'B2B logistics, property-related jobs, and regular transport contracts to keep your business operations running smoothly.', 'business-transport'],
];

export default function Services() {
  return <main className="overflow-hidden bg-background"><section className="container-wide pt-10 pb-20 md:pt-16 md:pb-28"><div className="flex flex-col gap-7 border-b border-navy/15 pb-12 md:flex-row md:items-end md:justify-between"><div><p className="font-display text-sm uppercase tracking-[.15em] text-gold">Our capabilities</p><h1 className="display-tight mt-4 max-w-3xl text-6xl text-navy md:text-8xl">Moving, handled <span className="text-gold">properly.</span></h1></div><p className="max-w-md text-base leading-7 text-ink-muted">From single item deliveries to complete office relocations, Charloxy Transport offers a diverse range of services tailored to your needs.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([title, description, slug], index) => <Link href={`/services/${slug}`} key={title} className="group flex min-h-[310px] flex-col rounded-2xl bg-paper p-7 transition-colors hover:bg-gold md:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs text-gold group-hover:text-navy/60">0{index + 1}</span><span className="grid size-10 place-items-center rounded-full border border-navy/15 text-navy transition-transform group-hover:rotate-45"><ArrowUpRight size={18} /></span></div><div className="mt-auto"><h2 className="max-w-sm font-display text-4xl uppercase leading-[.95] text-navy">{title}</h2><p className="mt-4 max-w-sm text-sm leading-6 text-ink-muted group-hover:text-navy/75">{description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-navy">Explore service <ArrowRight size={16} /></span></div></Link>)}</div><div className="mt-16 flex flex-col items-start justify-between gap-5 rounded-2xl bg-navy p-8 md:flex-row md:items-center md:p-10"><p className="font-display text-3xl uppercase text-background md:text-4xl">Need a service not listed here?</p><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-semibold text-navy">Contact us <ArrowRight size={16} /></Link></div></section></main>;
}
